default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  url: "postgresql://postgres:supersecretpassword@localhost:5433/pilates_db"

test:
  <<: *default
  url: "postgresql://postgres:supersecretpassword@localhost:5433/pilates_db"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
